sudo: false

env:
  global:
  - CC_TEST_REPORTER_ID=d58963d59360fa20e310efc96a9db90f25a1bb931d06cec3b77e7f745842caaf

language: php

php:
- 7.1
- 7.2

install:
- composer install
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- ./cc-test-reporter before-build

script:
- composer test-coverage
- composer cs-check

after_success:
- travis_retry composer upload-coverage

after_script:
- ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
